spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/${board.name}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: ${user.name}
    password : ${user.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
